//! Bit-exact fuzzy parity against upstream Ruby.
//!
//! `testdata/fuzzy_oracle.json` is generated by `scripts/gen-fuzzy-oracle.sh`
//! from upstream's actual `lib/fuzzy.rb` at the tag pinned in
//! `spec/UPSTREAM`. Scores compare via `f64::to_bits` — no epsilon, ever:
//! a tolerance is a place for drift to hide.

use serde::Deserialize;
use tryme_core::fuzzy;

#[derive(Deserialize)]
struct OracleRow {
    text: String,
    base_score: f64,
    query: String,
    score_bits: Option<u64>,
    score: Option<f64>,
    positions: Option<Vec<usize>>,
}

#[test]
fn matches_upstream_ruby_bit_for_bit() {
    let raw = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../testdata/fuzzy_oracle.json"
    ))
    .expect("oracle fixture missing — run scripts/gen-fuzzy-oracle.sh");
    let rows: Vec<OracleRow> = serde_json::from_str(&raw).expect("oracle must parse");
    assert!(rows.len() >= 100, "suspiciously small oracle");

    let mut checked = 0;
    for row in rows {
        let entries = vec![fuzzy::Entry::new((), &row.text, row.base_score)];
        let matches = fuzzy::match_entries(&entries, &row.query, None);
        match (row.score_bits, matches.first()) {
            (Some(bits), Some(m)) => {
                assert_eq!(
                    m.score.to_bits(),
                    bits,
                    "score mismatch for text={:?} query={:?}: ruby={:?} rust={:?}",
                    row.text,
                    row.query,
                    row.score,
                    m.score
                );
                assert_eq!(
                    Some(&m.positions),
                    row.positions.as_ref(),
                    "positions mismatch for text={:?} query={:?}",
                    row.text,
                    row.query
                );
                checked += 1;
            }
            (None, None) => checked += 1,
            (Some(_), None) => panic!(
                "ruby matched but rust filtered: text={:?} query={:?}",
                row.text, row.query
            ),
            (None, Some(m)) => panic!(
                "rust matched (score={}) but ruby filtered: text={:?} query={:?}",
                m.score, row.text, row.query
            ),
        }
    }
    assert!(checked >= 100);
}
