# @generated by usage-cli from try.usage.kdl
_tryme() {
    if ! type -p usage &> /dev/null; then
        echo >&2
        echo "Error: usage CLI not found. This is required for completions to work in tryme." >&2
        echo "See https://usage.jdx.dev for more information." >&2
        return 1
    fi

	local cur prev words cword was_split comp_args
    _comp_initialize -n : -- "$@" || return
    local spec_file="${TMPDIR:-/tmp}/usage__usage_spec_tryme.spec"
    cat >| "$spec_file" <<'__USAGE_EOF__'
name tryme
bin tryme
about "Ephemeral workspace manager — fuzzy-searchable, dated experiment directories"
long_about "A Rust port of tobi/try. The TUI renders on stderr and the chosen action is emitted as a shell script on stdout; the `try` shell function (from `tryme init`) evals it. Conformance target: tobi/try v1.9.3."
usage "Usage: tryme [OPTIONS] [COMMAND]"
flag "-h --help" help="Show help (printed to stderr)" global=#true
flag "-v --version" help="Show version (printed to stderr)"
flag --path help="Tries directory (default: ~/src/tries); last occurrence wins" {
    arg <PATH>
}
flag --no-colors help="Disable ANSI styling (NO_COLOR env is also honored)"
flag --no-expand-tokens help="Alias of --no-colors (historical name)"
flag --and-exit help="Render one frame and exit (test harness)" hide=#true
flag --and-type help="Pre-seed the input buffer (test harness)" hide=#true {
    arg <VALUE>
}
flag --and-keys help="Inject a key sequence (test harness)" hide=#true {
    arg <VALUE>
}
flag --and-confirm help="Substitute for delete-confirmation input; only literal YES confirms (test harness)" hide=#true {
    arg <VALUE>
}
flag --usage-spec help="Emit the usage KDL spec on stdout and exit" hide=#true
cmd init help="Output the `try` shell wrapper function" {
    arg "[ABS_PATH]" help="Absolute tries path baked into the wrapper (must start with /)" required=#false
}
cmd install help="Append the wrapper to your shell rc file (idempotent)" {
    arg "[ABS_PATH]" required=#false
}
cmd clone help="Clone a git repo into a date-prefixed try directory" {
    arg <GIT_URI>
    arg "[NAME]" required=#false
}
cmd worktree help="Create a detached worktree try from a git repo (or `dir` for the cwd)" {
    arg "[REPO|dir]" required=#false
    arg "[NAME]" required=#false
}
cmd exec help="Manual mode: emit the shell script on stdout (what the wrapper calls)" {
    arg "[]" required=#false double_dash=automatic
}
__USAGE_EOF__
    # shellcheck disable=SC2207
	_comp_compgen -- -W "$(command usage complete-word --shell bash -f "$spec_file" --cword="$cword" -- "${words[@]}")"
	_comp_ltrim_colon_completions "$cur"
    # shellcheck disable=SC2181
    if [[ $? -ne 0 ]]; then
        unset COMPREPLY
    fi
    return 0
}

if [[ "${BASH_VERSINFO[0]}" -eq 4 && "${BASH_VERSINFO[1]}" -ge 4 || "${BASH_VERSINFO[0]}" -gt 4 ]]; then
    shopt -u hostcomplete && complete -o nospace -o bashdefault -o nosort -F _tryme tryme
else
    shopt -u hostcomplete && complete -o nospace -o bashdefault -F _tryme tryme
fi
# vim: noet ci pi sts=0 sw=4 ts=4 ft=sh
